main_account_gbp:
  legal_entity: fintech_uk
  namespace: com.fintech.account
  name: main
  currency: GBP
  account_id: "*"

revenue_account_gbp:
  legal_entity: fintech_uk
  namespace: com.fintech.revenue
  name: general
  currency: GBP
  account_id: "*"

utilities_account_gbp:
  legal_entity: fintech_uk
  namespace: com.fintech.utilities
  name: electric
  currency: GBP
  account_id: "*"
