customer-facing-balance:
  time_axis: committed
  addresses:
    - main_account_gbp

interest-chargeable-balance:
  time_axis: committed
  addresses:
    - revenue_account_gbp

utilities-expense-balance:
  time_axis: committed
  addresses:
    - utilities_account_gbp
